### ISSUE TITLE
Having trouble building for Maya2019

### ISSUE THREAD

**Issue by PolyHound** [Autodesk/maya-usd#2120]
**Describe the issue**
In the begining I got Unicode Errors, so i put in --redirect-outstream-file=false flag to avoid those problems...
( "cp949" Errors... )
after putting --redirect-outstream flag in i didn't get any unicode Errors 
I found and checked solutions for ascii errors, but not this one. 

However what i'm getting now is

C:\myUsdBuild\include\pxr/imaging/hd/renderIndex.h : error C2220: warning treated as error - no 'object' file generated
 (compiling source file C:\mygit\maya-usd\plugin\adsk\plugin\plugin.cpp) [C:\mayaUSD\build\RelWithDebInfo\plugin\adsk\p
lugin\mayaUsdPlugin.vcxproj]
C:\myUsdBuild\include\pxr/imaging/hd/renderIndex.h : warning C4819: The file contains a character that cannot be repres
ented in the current code page (949). Save the file in Unicode format to prevent data loss (compiling source file C:\my
git\maya-usd\plugin\adsk\plugin\plugin.cpp) [C:\mayaUSD\build\RelWithDebInfo\plugin\adsk\plugin\mayaUsdPlugin.vcxproj]

cmake --build . --config RelWithDebInfo --target install -- /M:32

same goes with ninja setup

cmake --build . --config RelWithDebInfo --target install -- j32 

I've build pxr usd with "--build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"" flags in
and build in 64 / 84 / Developer vsStudio prompt shells and got all same errors..
Please give me some solutions about it...

**Build log**
[logs.txt](https://github.com/Autodesk/maya-usd/files/8093032/logs.txt)

**Specs:**
 - OS Windows 10
 - VS Studio 2017 / cmake 3.17 / ninja( latest ver )
 - Maya 2019
 - Maya USD commit for dev branch
 - Pixar USD v21.05

**Additional context**

**Comment by PolyHound** [comment]
forgot to write python version
Trying to compile in python 2.7.15 with conda -- same goes with pxr usd build

Just a little question with python.
 I tried to compile with Python 2.7.15 because Maya2019 works in 2.7.
But is it find to build  pxrUSD and this plugin with Python 3.7.7 for Maya2019?

**Comment by PolyHound** [comment]
I kind of figured it out by changing ""\myUsdBuild\include\pxr/imaging/hd/renderIndex.h"" file encoding into utf-8 and build well.

But when I load in to maya.. 

Freeze in creating usd stage from file

error: file: c:/program files/autodesk/maya2019/scripts/others/pluginwin.mel line 317: initializeplugin function failed (al_usdmayatestplugin) //

Attributes in USD not showing and lots of errors...


Is this about pxrUSD version i build? == 21.05 or Python version??
which ver should I try build for maya2019...

**Comment by seando-adsk** [comment]
Are part of our preflight system we are building MayaUsd using Maya 2019 and USD v21.05, so it should work for you.

I haven't seen a problem with renderIndex.h, but there was a problem with an invalid char in strategyBase.h that was fixed [here](https://github.com/PixarAnimationStudios/USD/commit/a16b0f093d3ab99ffe7ae524e145ec7f8fc88544). Perhaps renderIndex.h has a the same invalid char.

You will need to use python 2.7 to build both USD and MayaUsd since as you know Maya 2019 is using python 2.7.

After you fixed the renderIndex.h problem were you able to build mayaUsd successfully? If yes, are you able to load that plugin in Maya 2019? Are you setting ```MAYA_MODULE_PATH=C:\mayaUSD\install\RelWithDebInfo``` (your install folder where the mayaUsd.mod file is located)?

Sean

**Comment by PolyHound** [comment]
Yes the build went successful and I added MAYA_MODULE_PATH=C:\mayaUSD\install\RelWithDebInfo
I didn,t put in directly in system i added the variable using python and turn on maya by subprocess

I've build /20.11/21.05/21.08 in latest dev branch in python 2.7 and none of them worked...

I.ve tried setting qt location manually == this time plugin just dont load... ( Unable to dynamically load maya plugin )

Is it ok with building in the latest dev branch for maya 2019 ? If its yes what should I try out now...

**Comment by PolyHound** [comment]
As I said up I've build /20.11/21.05/21.08 in latest dev branch in python 2.7 and none of them working... 

Using vs2017 tested on cmake and ninja both same result
All build went successful and I added MAYA_MODULE_PATH=\install\RelWithDebInfo [ mayaUSD Path ] and I see the Plugin in maya plugin manager but I get lots of errors

- testPlugin doesn't load
// Error: file: .../Maya2019/scripts/others/pluginWin.mel line 317: initializePlugin function failed (AL_USDMayaTestPlugin) // 

- no Attribute appears and gives warning and errors about "lead" objects
// Error: line 1: 'lead' is an unknown RGB display color name 
// Warning: Failed to obtain selection highlight color for 'lead' objects //

- stage import option 
Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/getPluginResource.mel line 66: Plug-in resource lookup failed, resource ("mayaUsdPlugin","kCancel") is not registered

I checked same issue with "Stage Import Option" and the solution was setting QT manaully and i tried this 
with qt5.6.1 and 5.12.10 and if I build with manual QT location build was successful but maya now doesnt load any USDPlugins...  (  initializePlugin function failed )

I have tried everything i can think about so please help I have no idea why its not working...

**Comment by seando-adsk** [comment]
@PolyHound Can you try running the **tests** to make sure they are passing. Just add the flag ```--stages=test``` to your build.py command.

If they are passing then your build output is good so we need to figure out why it won't load. Are you able to load the ```mayaUsdPlugin``` in Maya or do you get the **initializePlugin** error? If you cannot load this plugin then one thing to check is to make sure you don't have any conflicting USD version in your environment. Start Maya and run ```getenv PATH``` and ```getenv PYTHONPATH``` and post the output here.

Sean

**Comment by seando-adsk** [comment]
The AL plugin and AL test plugin **cannot** be loaded at the same time. You should not need to load the Test plugin, it is for running the unit tests. 

If you want to build with Qt, then for Maya 2019 you need to use Qt 5.6.1. If it works you should see the message, "Building with Qt features enabled" in your build log.

If you load just the **mayaUsdPlugin** does it work? If not, can you disable the autoloading of the three plugins and then manually load the mayaUsdPlugin and attach the output from the Script Editor.

**Comment by PolyHound** [comment]
Good to know it was not a problem for testPlugins

I've disabled all autoLoad and loaded just mayaUsdPlugin ( plugin in adsk/plugin ) and got this error on load

// Error: file: C:/USD/mayaUSD_21.05/install/RelWithDebInfo/plugin/adsk/scripts/mayaUsdMenu.mel line 433: Invalid flag '-optionVarChanged' // 

I think the error comes up when i hover to "Select"(next to "Create") tab


testing with "Kitchen_set" from pxr Doc 
maya crash on import or select in kitchen instanced set usd example -- (stage import)
( not crashing on usd which is not the instanced file)
I'm not sure this is a problem since i dont have much knowledge about usd in this point...   just let you know....

and

- no Attribute appears except the root of the usdTree in outliner and gives warning or errors about "lead" objects on selection from outliner
// Error: line 1: 'lead' is an unknown RGB display color name
// Warning: Failed to obtain selection highlight color for 'lead' objects //

- selecting "stage import" option on UI
Error: file: C:/Program Files/Autodesk/Maya2019/scripts/others/getPluginResource.mel line 66: Plug-in resource lookup failed, resource ("mayaUsdPlugin","kCancel") is not registered

still not going away....

will these errors go away if i build with QT 5.6.1??
I've tried this building with QT and plugins wont load to maya 
but i'm not sure that was build with 21.05ver 
so i wonder if its worth a try with building with QT

**Comment by seando-adsk** [comment]
What exact version of Maya 2019 are you using? We support 2019 Update 3. The flag ```optionVarChanged``` was added in 2019.2.  It could be that script error is throwing off the proper registration of the plugin. Can you try with 2019.3 or at least edit the file ```C:/USD/mayaUSD_21.05/install/RelWithDebInfo/plugin/adsk/scripts/mayaUsdMenu.mel``` and comment out the lines with the ```optionVarChanged```. 

You will need to build with Qt if you want to use the **Hierarchy View** (available from the USD Import Options dialog) or the **Layer Editor**. You don't need Qt if you just want to use USD import.

Your last sentence is correct. Maya 2019 (and Maya 2020) both only have Ufe v1 so there is no Attribute Editor support.

Sean

**Comment by PolyHound** [comment]
I'm working with maya 2019.3.1 the whole time so i guess i should go and comment out that line

and i'll try build with qt again

**Comment by PolyHound** [comment]
Yes!!! Finally I think its working Thank you!!
Layer Editor opens and stage import option show up.
Before closing, this is my first time building somthing and Beginner for USD, so I have few questions.


- Can I delete build folders including pxrUSD buildFolder? // Its a big folder so if they are just for building can I delete it?

- Is it ok removing testPlugins? and how can I remove them?  // since the build went successfully I dont think I need test plugin anymore

- What is the errors and warning about "leads" object... is it about materials not supporting? ( It went away when I activated hydra and I dont have Renderman on Maya )

- Maya crashes on import or select in kitchen instanced set usd example form pxr Doc == Is this not a problem??


Really appreciate for all your Supports!!!!
Thank you

**Comment by seando-adsk** [comment]
That is good news.

- As long as you don't need to make any changes or rebuild USD, then yes you should be able to delete the folders ```C:/USD/pxrUSD_21.05/build``` (this is the largest) and ```C:/USD/pxrUSD_21.05/src```. But do **not** delete the bin/lib/plugin folders, you need these for running.
- You are right you don't need the tests anymore. You can delete ```AL_USDMayaTestPlugin.mll```. You can also delete the build folder ```C:\mayaUSD\build\RelWithDebInfo```.
- I'm not familiar with the error about "leads" object. I'll have someone else take a look.
- I'll ask our QA to test the crash. 

Sean

**Comment by PolyHound** [comment]
Ok, got it! Thank you once again.

**Comment by PolyHound** [comment]
This questions is not about building but got some question playing around with my build plugin

Is usdPlugin maya2019  only supports import/export and simple transform edits?

I cant find how to change varients or change usdTree from outliner or making new "def" or "xform" objects and reference objects. I found varient could be change in import Hierarchy View but cant be changed after it is imported.

if it is not editable in maya, I wonder if it can be done by python commands...?
Does having only Ufe v1 so no Attribute Editor support means I can't edit usdFileDatas( varients/reference... ) and just can be used for visualize and export propose?

**Comment by seando-adsk** [comment]
Yes you are correct, the support in Maya 2019 is limited. All the context menu functionality that we added to prims in the Outliner (to add new prims, change variants, etc) needs Ufe v2 which is only in Maya 2022 (or later). Same reason there is no Attribute Editor support - it needs Ufe v2.

The only way to do what you want in Maya 2019 would be by using the Pixar Usd python API and limited python wrappers MayaUsd supports for Ufe v1 to directly manipulate the prims.

Sean

**Comment by santosd** [comment]
Hi @PolyHound, thank you for logging this issue. Since @seando-adsk was able to answer the original question, I am going to go ahead and close this issue out. However, if you have any further questions regarding workflows, feel free to log a [discussion](https://github.com/Autodesk/maya-usd/discussions) or if you come across a bug or issue feel free to log another [issue](https://github.com/Autodesk/maya-usd/issues)

Thanks again and glad to have you as a user.
