### ISSUE TITLE
Unable to compile on macOS 10.15.3 - Boost Symbols Not Found

### ISSUE THREAD

**Issue by ZbadhabitZ** [Autodesk/maya-usd#334]
During the build process, the following error can be noted;

```
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      __GLOBAL__sub_I_proxyShapeBase.cpp in proxyShapeBase.cpp.o
      __GLOBAL__sub_I_material.cpp in material.cpp.o
      pxrInternal_v0_20__pxrReserved__::UsdMayaUtilFileSystem::resolveRelativePathWithinMayaContext(Autodesk::Maya::OpenMaya20200000::MObject const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in utilFileSystem.cpp.o
      __GLOBAL__sub_I_utilFileSystem.cpp in utilFileSystem.cpp.o
  "boost::system::generic_category()", referenced from:
      __GLOBAL__sub_I_proxyShapeBase.cpp in proxyShapeBase.cpp.o
      __GLOBAL__sub_I_material.cpp in material.cpp.o
      __GLOBAL__sub_I_utilFileSystem.cpp in utilFileSystem.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [lib/libmayaUsd.dylib] Error 1
make[1]: *** [lib/CMakeFiles/mayaUsd.dir/all] Error 2
make: *** [all] Error 2
```

The Boost component is noted to be installed, as was required during the build process for Pixar's USD tools, but cannot seem to be found

**Build log**
(see attached)
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4296854/build_log.txt)

**Specs:**
 - macOS 10.15.3
 - Xcode 11.3.1
 - Maya 2020
 - Maya USD commit SHA (dev at 176f60e)
 - Pixar USD commit SHA (dev at 40c8134)

**Comment by HamedSabri-adsk** [comment]
Hi @ZbadhabitZ,
Catalina is still at experimental stage for us. Can you post here how you are building USD?
Thanks.

**Comment by ZbadhabitZ** [comment]
Absolutely.  I am receiving the aforementioned error when running the following;

`/Applications/Autodesk/maya2020/Maya.app/Contents/bin/mayapy build.py --generator Ninja --build-args=-DCMAKE_MAKE_PROGRAM='/Users/brandon/Downloads/ninja' --maya-location /Applications/Autodesk/maya2020 --pxrusd-location /Users/brandon/Projects/Pixar/BUILD/USD ~/Desktop/BUILD`

**Comment by HamedSabri-adsk** [comment]
I actually meant pixar USD itself. I assume you used "build_usd.py" to build it? 

Also, you don't really need to build maya-usd project using mayapy as it is shown in doc:

https://github.com/Autodesk/maya-usd/blob/dev/doc/build.md#5-how-to-use-buildpy-script

**Comment by ZbadhabitZ** [comment]
I'm a bit confused, then.  The instructions do say to use mayapy on macOS, toward the bottom, under **Additional Build Instruction** and the _Python_ section.

I installed the Pixar USD toolkit using the following;

```
cd $HOME
mkdir Projects
cd Projects
mkdir Pixar
cd Pixar
git clone https://github.com/PixarAnimationStudios/USD
cd USD
git checkout dev
cd ..
python USD/build_scripts/build_usd.py -v $HOME/Projects/Pixar/BUILD/USD
```

I am able to successfully use the USD tools, per testing with _usdview_, which launches the relevant GUI successfully when referencing an existing local USD file.  Thanks!

**Comment by HamedSabri-adsk** [comment]
`I'm a bit confused, then. The instructions do say to use mayapy on macOS, toward the bottom, under Additional Build Instruction and the Python section.`

correct, this only applies to Pixar USD only and not Maya USD as per explanation under **Additional Build Instruction/Python**

Also before that, there is a section about boost that you are missing when building USD and is most likely why you are having a problem:

The upshot is, build Pixar USD as follow:

`/Applications/Autodesk/maya2020/Maya.app/Contents/bin/mayapy  USD/build_scripts/build_usd.py $HOME/Projects/Pixar/BUILD/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"`

**Comment by ZbadhabitZ** [comment]
Thanks for the replies.  When following your guidance (I've also removed the existing built USD binaries from my PATH, for posterity), I run the following;

`/Applications/Autodesk/maya2020/Maya.app/Contents/bin/mayapy USD/build_scripts/build_usd.py $HOME/Projects/Pixar1/BUILD/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"`

This results in the error;
`ERROR: Cannot build usdview when building against Maya's version of Python. Maya does not provide access to the 'OpenGL' Python module. Use '--no-usdview' to disable building usdview.`

I can confirm that PyOpenGL is installed and the site-packages do exist in my PYTHONPATH, per;
```
bash-3.2# echo $PYTHONPATH
/Library/Python/2.7/site-packages:/Users/brandon/Library/Python/2.7/lib/python/site-packages
```

Subsequently, when I attempt to run the install using '--no-usdview', I receive the following;
```
CMake Error at /usr/local/lib/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Could not find a package configuration file provided by "boost_python"
  (requested version 1.72.0) with any of the following names:

    boost_pythonConfig.cmake
    boost_python-config.cmake

  Add the installation prefix of "boost_python" to CMAKE_PREFIX_PATH or set
  "boost_python_DIR" to a directory containing one of the above files.  If
  "boost_python" provides a separate development package or SDK, be sure it
  has been installed.
```

I can confirm that both Boost and Boost-Python have been installed via Brew.

**Comment by ZbadhabitZ** [comment]
Subsequent update:  I uninstalled both Boost and Boost-Python from my system (via brew uninstall boost-python and brew uninstall boost).  I was then able to install the Pixar USD tools via command line using mayapy (no usdview).

When then attempting to install the Maya USD plug-in, per this command,
`python build.py --maya-location /Applications/Autodesk/maya2020/ --pxrusd-location /Users/brandon/Projects/Pixar1/BUILD/USD/ ~/Desktop/BUILDA`

I receive the following;
```
Traceback (most recent call last):
  File "/Users/brandon/Projects/Pixar1/BUILD/USD/bin/usdGenSchema", line 47, in <module>
    from pxr import Plug, Sdf, Usd, Vt, Tf
  File "/Users/brandon/Projects/Pixar1/BUILD/USD/lib/python/pxr/Plug/__init__.py", line 28, in <module>
    from . import _plug
ImportError: dlopen(/Users/brandon/Projects/Pixar1/BUILD/USD/lib/python/pxr/Plug/_plug.so, 2): Library not loaded: @executable_path/../Frameworks/Python.framework/Python
  Referenced from: /Users/brandon/Projects/Pixar1/BUILD/USD/lib/python/pxr/Plug/_plug.so
  Reason: unsafe use of @executable_path in /Users/brandon/Projects/Pixar1/BUILD/USD/lib/python/pxr/Plug/_plug.so with restricted binary (Codesign main executable with Library Validation to allow @ paths)
CMake Error at lib/usd/schemas/CMakeLists.txt:46 (message):
  Schemas generation failed
```

**Comment by HamedSabri-adsk** [comment]
No problem. Ugh right. We have a PR ready that removes the `if isMayaPython:` method in `build_usd.py` but it is not in dev yet.

So here is what you need to do before building the USD project:

1- delete `if isMayaPython` statement ( line 1811-1824
https://github.com/PixarAnimationStudios/USD/blob/40c813421425c47aa84f4572b4798fbb3430984e/build_scripts/build_usd.py#L1811

2- run `export PYTHONPATH=$PYTHONPATH:Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages`

Also make sure you have a ll the necessary packages explained under **Additional Build Instruction**.  PyOpenGL, PyYAML, PySide2, Jinja2, etc...

Hope this helps.

**Comment by HamedSabri-adsk** [comment]
That's a problem. You do want to build USD **with** `usdview` because if you don't then "usdGenSchema" won't be created which is a necessary tool for generating schemas and this failure message confirms it: `Schemas generation failed`

I bet, if you look at your `$HOME/Projects/Pixar/BUILD/USD/bin` you won't see `usdGenSchema` :)

**Comment by ZbadhabitZ** [comment]
Thanks for following up.  I have completely restarted my USD install, using your guidance regarding mayapy.  USD installs successfully, and I can confirm `usdview` functions normally, but when attempting to install the Maya plug-in, I run into the same references error regarding the dlopen.

I am using this command;
`python build.py --maya-location /Applications/Autodesk/maya2020/ --pxrusd-location /Users/brandon/Projects/Pixar1/BUILD/USD/ ~/Desktop/BUILDA`

**Comment by HamedSabri-adsk** [comment]
Catalina is still at the experimental stage. I will build things on Catalina sometimes this week to see if I can reproduce the problem and fix it.

**Comment by ZbadhabitZ** [comment]
I was able to successfully build the Maya plug-in by disabling System Integrity Protection (booting into Recovery Mode and running `csrutil disable`), then restarting and attempting the build.  While not an ideal solution, it did seem to allow for Python to load the necessary dependencies and complete the build.

Regretfully, even after setting my Maya environment variable to point to the install directory (which is confirmed to have the .mod file), Maya does not see this folder nor list the Maya USD plug-ins in the Plug-In Manager.

**Comment by ZbadhabitZ** [comment]
Subsequent update; I have succeeded in fully building and installing the Pixar USD tools, Maya USD plug-in, and can now import/export USD files in Maya 2020 on macOS Catalina.  In case it is helpful, these are the full steps I took, per your expert guidance and support;

**1) Ensure Prerequisites Are Installed**
- Verify installation of Xcode
- Verify installation of Maya 2020
- Install Python-based dependencies;
```
sudo pip install pyyaml
sudo pip install pyside2
sudo pip install pyopengl
sudo pip install jinja2
```

**2) Download and Build Pixar USD (Using Maya's Python Binaries)**
```
cd $HOME
mkdir Projects
cd Projects
git clone https://github.com/PixarAnimationStudios/USD
cd USD
git checkout dev
cat build_scripts/build_usd.py
```

Remove lines 1811 - 1824 (all of the `if IsMayaPython` statement).  Save and exit.

```
cd ..
export PYTHONPATH=$PYTHONPATH:Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages:Library/Python/2.7/site-packages
/Applications/Autodesk/maya2020/Maya.app/Contents/bin/mayapy USD/build_scripts/build_usd.py $HOME/Projects/Pixar/BUILD/USD --build-args boost,"--with-date_time --with-thread --with-system --with-filesystem"
export PATH=$PATH:$HOME/Projects/Pixar/BUILD/USD/bin
export PYTHONPATH=$PYTHONPATH:$PATH/Projects/Pixar/BUILD/lib/python
```

**3) Disable System Integrity Protection**
- Restart computer
- Hold _Option+R_ upon reboot to boot into Recovery Mode
- Utilities -> Terminal
- `csrutil disable`
- Press enter.  Reboot to normal login.

**4) Build Maya USD Plug-In**
```
cd $HOME
cd Projects
git clone https://github.com/Autodesk/maya-usd.git
cd maya-usd
python build.py --maya-location /Applications/Autodesk/maya2020/ --pxrusd-location $HOME/Projects/Pixar/BUILD/USD/ $HOME/Projects/Maya/
```

**5) Set Maya Module Path**
`nano $HOME/Library/Preferences/Autodesk/maya/2020/Maya.env`
Add `MAYA_MODULE_PATH=$HOME/Projects/Maya/install/RelWithDebInfo` to file.  Save and exit.

**6) Enable Plug-in via Maya Plug-In Manager**
- Launch Maya 2020
- Windows -> Settings/Preferences -> Plug-In Manager
- Search "usd" and load/auto-load desired plug-ins

**7) Enable System Integrity Protection**
- Restart computer
- Hold _Option+R_ upon reboot to boot into Recovery Mode
- Utilities -> Terminal
- `csrutil enable`
- Press enter.  Reboot to normal login.

**Comment by aka-anoop** [comment]
Followed the above, However, While using DevKit to build *UFE*
## 2019
USD Version: v20.02

The following works as long as I don't pass the devkit path to build UFE. As soon as --devkit-location is passed, I get the following
```
ld: warning: ignoring file /Users/anoop/tools/devkitBase2019/devkit/ufe/lib/libufe_1.dylib, file was built for unsupported file format ( 0xCF 0xFA 0xED 0xFE 0x07 0x00 0x00 0x01 0x03 0x00 0x00 0x00 0x0A 0x00 0x00 0x00 ) which is not the architecture being linked (x86_64): /Users/anoop/tools/devkitBase2019/devkit/ufe/lib/libufe_1.dylib
Undefined symbols for architecture x86_64:
```
Here is the build command used
```
/Applications/Autodesk/maya2019/Maya.app/Contents/bin/mayapy build.py --maya-location /Applications/Autodesk/maya2019 --pxrusd-location /opt/usd --devkit-location /Users/anoop/tools/devkitBase2019 /Users/anoop/tools/maya-usd --install-location=/Users/anoop/tools/maya-usd/2019
```
### Log
[build_log.txt](https://github.com/Autodesk/maya-usd/files/4324945/build_log.txt)

I had to pass `--build-args="-DCMAKE_WANT_UFE_BUILD=OFF"` to make it work

## 2020
Works fine without errors
```
/Applications/Autodesk/maya2020/Maya.app/Contents/bin/mayapy build.py --maya-location /Applications/Autodesk/maya2020 --pxrusd-location /opt/usd --devkit-location /Users/anoop/tools/devkitBase2020 /Users/anoop/tools/maya-usd --install-location=/Users/anoop/tools/maya-usd/2020

    Building with settings:
      Source directory          /Users/anoop/code/blog/maya-usd
      Workspace directory       /Users/anoop/tools/maya-usd
      Build directory           /Users/anoop/tools/maya-usd/build/RelWithDebInfo
      Install directory         /Users/anoop/tools/maya-usd/2020
      Variant                   RelWithDebInfo
      Python Debug              Off
      CMake generator           Default
      Build Log                 /Users/anoop/tools/maya-usd/build/RelWithDebInfo/build_log.txt
      Stages arguments          ['clean', 'configure', 'build', 'install']
Success MayaUSD build and install !!!!
Elapsed time: 00:09:06
```

**Comment by juanfernandez** [comment]
Hello, i'm trying to compile MayaUSD plugin in almost 1 week, I've done a fresh start of macOS Catalina 10.15.4 installation with nothing more that Maya 2020, Xcode, Python2.7+ Python-based dependencies, I was follow every step that ZbadhabitZ suggested and only got errors plus errors.

The common error start here:

CMake Warning at lib/CMakeLists.txt:18 (add_library):
  Cannot generate a safe runtime search path for target mayaUsd because there
  is a cycle in the constraint graph:

Attached error log (Maya 2019 and Maya 2020).

[maya2019.txt](https://github.com/Autodesk/maya-usd/files/4429631/maya2019.txt)
[maya2020.txt](https://github.com/Autodesk/maya-usd/files/4429632/maya2020.txt)

Thank you!

**Comment by HamedSabri-adsk** [comment]
Hi @juanfernandez 

Please ignore the warnings ( Cannot generate a safe runtime search ) there should not be a problem. I am already aware of them and should have them fixed hopefully soon.

I believe your problem is because you don't have Xcode CommandLineTools installed. :) 
Once you install Xcode CommandLineTools , you should see c/c++ compilers working and that should solve your problem.

```
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
```

Other things I noticed in your log:

1-
You don't need this step after building USD. this is done automatically via cmake/usd.cmake
```
jfersep@Dark-Army Projects % export PATH=$PATH:$HOME/Projects/Pixar/BUILD/USD/bin
jfersep@Dark-Army Projects % export PYTHONPATH=$PYTHONPATH:$PATH/Projects/Pixar/BUILD/lib/python
```
2- You are not passing devkit and Qt and therefore some of the important features of mayaUsd won't be available. Just something to be aware of.
```
-- UFE not found. UFE features will be disabled.
-- QT_LOCATION not set. Building Qt features will be disabled.
```

**Comment by juanfernandez** [comment]
Hello Ahmed Sabri-adsk, sorry for the delayed response... I was trying your suggestions and still have errors.

Programs installed:

Command_Line_Tools_for_Xcode_11.4
qt-opensource-mac-x64-5.12.7

Build command:

python build.py --maya-location /Applications/Autodesk/maya2020/ --pxrusd-location $HOME/Projects/Pixar/BUILD/USD/ --devkit-location /opt/local/devkitBase/maya2020 --qt-location /Users/jfersep/Qt5.12.7/5.12.7/clang_64/lib/cmake/Qt5 $HOME/Projects/Maya/

Error log:

[maya2020.txt](https://github.com/Autodesk/maya-usd/files/4430526/maya2020.txt)

Thank you!

**Comment by HamedSabri-adsk** [comment]
Hmmm, very strange.  Looking at your previous and recent logs in more details and everything seems normal. I don't see anything wrong with your clang compiler and your build flags/settings looks correct to me.  I will try to have a closer look at your log and see what I find.

**Comment by juanfernandez** [comment]
> Hmmm, very strange. Looking at your previous and recent logs in more details and everything seems normal. I don't see anything wrong with your clang compiler and your build flags/settings looks correct to me. I will try to have a closer look at your log and see what I find.

Thank you so much!

**Comment by kxl-adsk** [comment]
@juanfernandez We have been able to successfully build on Catalina. Do you still have build issues or this ticket can be closed?

**Comment by juanfernandez** [comment]
I'm trying again to build USD in Catalina, I was never to be able to fix
the build issue. 

El 2020-06-09 15:17, Krystian Ligenza escribió:

> @juanfernandez [1] We have been able to successfully build on Catalina. Do you still have build issues or this ticket can be closed? 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub [2], or unsubscribe [3].

-- 

Atte.
Juan Fernandez
Software Engineer
 

Links:
------
[1] https://github.com/juanfernandez
[2]
https://github.com/Autodesk/maya-usd/issues/334#issuecomment-641518339
[3]

**Comment by kxl-adsk** [comment]
If you have any new info to add, please let us know. If you already succeeded, let's close this ticket.

**Comment by ZbadhabitZ** [comment]
I have confirmed success on macOS 10.15/Catalina.  I have not tested this installation on macOS 11/Big Sur, but suggest closing this ticket as I was able to resolve.
