### ISSUE TITLE
Edit- Duplicate as Maya data feature bug & PrimUpdaterManager import error

### ISSUE THREAD

**Issue by Ennosch** [Autodesk/maya-usd#1860]
Hi, 

there seems to be a problem with the Edit - Duplicate as Maya data feature in the current 0.14.0 release.

Steps to reproduce:
- go the Layer Editor, create a new stage
- go the outliner add 2 new primitives to the stage (I added a Cube and a Cylinder)
- unfold the all outliner's content (Shape ticked on) right click on a prim and click Edit as Maya data or Duplicate as Maya data.
![image](https://user-images.githubusercontent.com/15966486/143443970-eb71b099-9745-4fcd-9e1b-5d26db049a5d.png)

The Error I am getting is:
```
# Error: file: /usr/autodesk/mayausd/maya2022/0.14.0_202111080638-e137fb5/mayausd/MayaUSD3/plugin/adsk/scripts/USDMenuProc.mel line 23: ImportError: file <maya console> line 1: cannot import name 'PrimUpdaterManager' from 'mayaUsd.lib' (/usr/autodesk/mayausd/maya2022/0.14.0_202111080638-e137fb5/mayausd/MayaUSD3/lib/python/mayaUsd/lib/__init__.py) # 
```
which you could also obtain typing `from mayaUsd.lib import PrimUpdaterManager` in the python console.

I think this is the relevant merge right ?
https://github.com/Autodesk/maya-usd/pull/1789

this happening on:
`CentOS-7` using `maya2022-2` with the latest `maya_usd-0.14.0` release 
https://github.com/Autodesk/maya-usd/releases/tag/v0.14.0

I. Is this feature excpected to work in the current 0.14.0 release ?
II. Does bug link to other issues or threads ?

keep it up :)

**Comment by kxl-adsk** [comment]
Thanks for reporting @Ennosch. This is a Maya beta feature and it shouldn't be even available for released versions of Maya yet. FYI. @ppt-adsk.

BTW. We have a separate forum where we discuss beta features for unreleased versions of Maya. If you have any other questions regarding "Duplicate/Edit As Maya Data", please go to our beta forums. If you don't have access, we can figure out a way to get you on it.

**Comment by wtelford** [comment]
Hey @santosg87 can you log an action item for this.

**Comment by oumad** [comment]
Hello there,
I just noticed this issue, and as @Ennosch mentioned exactly, basically `mayaUsd.lib` doesn't have `PrimUpdaterManager`. But from what @kxl-adsk says. I understand this is simply not in the current maya releases.
@kxl-adsk  I'm currently doing a lot of what I see lacking in the current maya releases through scripting for our pipeline. Is there a way for me to access this beta forum? It would help me a lot to have a better vision of what's possibly coming, would love to see your discussions there !
Thank you.

**Comment by kxl-adsk** [comment]
@oumad I will need your email for the invite. Found one on GitHub that I will try to reach you.

**Comment by daviddeacon** [comment]
Looks like this UI command is in the latest public release 0.14.0 and was mentioned in the change logs under workflow.

"Edit as Maya data / Merge back to USD"

**Comment by neilrubie** [comment]
I was wondering if I could also have access to this beta forum to see and discuss ideas regarding forthcoming mayaUsd functionality? We are making use of the latest MayaUsd plugin builds and building solutions of our own, so it would be nice to know what may be coming down the pipe.

**Comment by kxl-adsk** [comment]
@neilrubie I can't seem to find anywhere on GitHub your email address. We will need it for the invite.

Not sure if you want to leave it here...or just message me on linked-in/email. Pick your favorite.

**Comment by neilrubie** [comment]
Reached out through LinkedIn, thanks!

**Comment by santosg87** [comment]
closing this one, as it should be fixed now - as this was a beta feature, we removed the mentions and UI from 2022. :)
