### ISSUE TITLE
Fails to build against USD 22.x

### ISSUE THREAD

**Issue by dgovil** [Autodesk/maya-usd#2269]
**Describe the issue**
A change introduced in https://github.com/Autodesk/maya-usd/pull/2177/commits/18e2cdebcda15a2a2276e316740ab24b445e97c2 seems to stop Maya USD building against any USD 22.x version.

There's a few different implementations of GetRenderTag and it's not clear to me based on this context which one should be called.

**Build log**
```
/Users/dhruvgovil/Projects/maya-usd/lib/mayaUsd/render/vp2RenderDelegate/mayaPrimCommon.cpp:580:20: error: use of undeclared identifier 'GetRenderTag'; did you mean '_RenderTag'?
    _RenderTag() = GetRenderTag();
                   ^~~~~~~~~~~~
                   _RenderTag
```

**Specs:**
 - OS & version macOS 12.3
 - Compiler & version clang 13
 - Maya version : Maya 2020/2022
 - Maya USD commit SHA 01a560d621552096ea691caa523d26bc17a6d209
 - Pixar USD commit SHA 857ffda41f4f1553fe1019ac7c7b4f08c233a7bb

**Additional context**
Seems to be a regression. I did a build successfully against 22.3 prior to that PR being merged in.

**Comment by gracekumagai** [comment]
We are encountering the same issue when building against USD release v22.03

**Comment by dj-mcg** [comment]
I just submitted a pull request with a fix for this:
https://github.com/Autodesk/maya-usd/pull/2288

**Comment by dgovil** [comment]
Thanks for the quick turnaround @dj-mcg

**Comment by dj-mcg** [comment]
np!!

**Comment by santosg87** [comment]
@dgovil @gracekumagai @dj-mcg it sounds like the work for this is done. is it OK for me to close this issue?

**Comment by dgovil** [comment]
@santosg87 yep seems to be good to close. Cheers!
