### ISSUE TITLE
Problems building on windows

### ISSUE THREAD

**Issue by JesseFK** [Autodesk/maya-usd#176]
Hi,

I've been trying to build on windows for Maya 2019.00 but it keeps feeling no matter what I try. I'm not really an expert at this so I'm having a hard time figuring out why it fails too. I've successfully built pixarUSD so that should be fine I think.

I attached the build_log. The only errors that I get are these:

C:\thirdparty\USD\Maya-USD\maya-usd-0.0.2\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(305): error C2672: 'SdfPathFindLongestPrefix': no matching overloaded function found [C:\usd-maya\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]

C:\thirdparty\USD\Maya-USD\maya-usd-0.0.2\plugin\pxr\maya\lib\usdMaya\shadingModeExporterContext.cpp(305): error C2780: 'BidirectionalIterator pxrInternal_v0_19__pxrReserved__::SdfPathFindLongestPrefix(BidirectionalIterator,BidirectionalIterator,const pxrInternal_v0_19__pxrReserved__::SdfPath &)': expects 3 arguments - 2 provided [C:\usd-maya\build\RelWithDebInfo\plugin\pxr\maya\lib\usdMaya\usdMaya.vcxproj]

Other than that there's a lot of warnings about the findPlug and setInternalValueInContext methods.

**Build Log:**
[build_log.txt](https://github.com/Autodesk/maya-usd/files/3956483/build_log.txt)

**Comment by BigRoy** [comment]
The errors you are facing appear to me as if you're compiling against an incompatible version of USD.

It seems you are building against USD `0.19.5` which is likely invalid for what you're building. What Branch of Maya-USD are you trying to compile? Say you'd compile against the `dev` branch then [here is where you'll find the matching USD version you'll need](https://github.com/Autodesk/maya-usd/blob/dev/doc/DEVELOPER.md#source-versions). Each branch has this `/doc/DEVELOPER.md` file stating what `USD` is compatible with it.

I'd recommend pulling the relevant commit of `USD` for the branch you're trying to compile. Then compile that version of USD and try again. 👍 

> Other than that there's a lot of warnings about the findPlug and setInternalValueInContext methods.

These happen indeed, you can ignore them for now.

**Comment by JesseFK** [comment]
Thanks that worked!
